const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  citizenId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  reportedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  title: { type: String, default: '' },
  image: { type: String, default: '' },
  images: [{ type: String }],
  imageData: { type: Buffer, default: null },
  imageMimeType: { type: String, default: '' },
  category: { type: String, required: true, trim: true },
  description: { type: String, required: true, trim: true },
  severity: { type: String, enum: ['low', 'moderate', 'high', 'critical'], default: 'moderate' },
  confidence: { type: Number, default: 0 },
  healthRisk: { type: String, default: 'unknown' },
  recommendation: { type: String, default: '' },
  pollutionDetected: { type: Boolean, default: false },
  reason: { type: String, default: '' },
  estimatedPM25Impact: { type: String, default: '' },
  estimatedPM10Impact: { type: String, default: '' },
  emergencyLevel: { type: String, default: 'Green' },
  needsMunicipalAction: { type: Boolean, default: false },
  possibleSource: { type: String, default: '' },
  priority: { type: String, default: 'Medium' },
  municipalStatus: { type: String, enum: ['pending', 'under_review', 'team_assigned', 'in_progress', 'resolved'], default: 'pending' },
  assignedOfficer: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  assignedOfficerName: { type: String, default: '' },
  assignedTeam: { type: String, default: '' },
  statusUpdatedAt: { type: Date },
  resolvedAt: { type: Date },
  officerRemarks: { type: String, default: '' },
  reviewHistory: [{
    officer: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    action: { type: String, enum: ['status', 'municipalStatus', 'priority', 'remarks'] },
    value: { type: String },
    reviewedAt: { type: Date, default: Date.now }
  }],
  location: { type: String, required: true, trim: true },
  latitude: { type: Number, default: 0 },
  longitude: { type: Number, default: 0 },
  AQI: { type: Number, default: 0 },
  aqiLevel: { type: String, default: '' },
  PM25: { type: Number, default: 0 },
  PM10: { type: Number, default: 0 },
  CO: { type: Number, default: 0 },
  NO2: { type: Number, default: 0 },
  O3: { type: Number, default: 0 },
  temperature: { type: Number, default: 0 },
  humidity: { type: Number, default: 0 },
  prediction: { type: String, default: '' },
  status: { type: String, enum: ['pending', 'verified', 'in_progress', 'resolved', 'rejected', 'Reported', 'AI Analyzed', 'Action Scheduled'], default: 'pending' },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Report', reportSchema);
